spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/university_management?useSSL=false&serverTimezone=UTC
    username: root
    password:   # Change to your MySQL root password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: efa3e0c69aaf15e86288c07b329466292d9cdf13f5c75becc3e031cc3f885247
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  web:
    resources:
      static-locations: file:./avatars/
